package com.myspace.it_orders;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ITOrderService implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public ITOrderService() {
    }




}